# Base Assignment

# POST /guests

# Test for 201 response code

#   Setup calls

#   Tests calls

# Test for 400 response code

#   Setup Calls

#   Tests Calls

# Test for 409 response code

#   Setup calls

#   Tests calls